- name: Installing nginx and running it
  hosts: all
  gather_facts: False
  become: yes


  tasks:
   - name: updating
     apt: update_cache=yes
     become: yes
   - name: Nginx setup
     apt: name=nginx state=latest
     become: yes
   - name: start nginx
     service:
       name: nginx
       state: started
     become: yes
   - name: index.html copy
     copy:
       src: index.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644
   - name: restart nginx
     service:
       name: nginx
       state: restarted
     become: yes
...